"""
Django settings for cwc project.

Generated by 'django-admin startproject' using Django 1.11.16.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Retrieve production stage environment variable
class MissingEnvironmentVariable(Exception):
    pass

class InvalidEnvironmentVariable(Exception):
    pass

try:
    STAGE = os.environ['STAGE']
except KeyError:
    raise MissingEnvironmentVariable('Environment variable STAGE is not defined.')

# SECURITY WARNING: don't run with debug turned on in production!
if STAGE == 'development' or STAGE == 'staging':
    DEBUG = True
elif STAGE == 'production':
    DEBUG = False
else:
    raise InvalidEnvironmentVariable('The value of environment variable STAGE is not valid.')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY_FILE = '%s/auth/secret.txt' % BASE_DIR
with open(SECRET_KEY_FILE, 'r', encoding='utf8') as f:
    content = f.readline()
SECRET_KEY = content[:-1]

if STAGE == 'development':
    ALLOWED_HOSTS = [
        'localhost',
    ]
elif STAGE == 'staging':
    ALLOWED_HOSTS = [
        'staging.coolwatercreations.com',
    ]
elif STAGE == 'production':
    ALLOWED_HOSTS = [
        'coolwatercreations.com',
        'www.coolwatercreations.com',
    ]


# Application definition

INSTALLED_APPS = [
    'users',
    'gallery',
    'about',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'cwc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'gallery/templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cwc.context_processors.stage',
            ],
        },
    },
]

WSGI_APPLICATION = 'cwc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

with open(os.path.join(BASE_DIR, 'auth/.pgpass'), 'r', encoding='utf8') as f:
    content = f.readline()
PGPASSWORD = content[12:-1]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'cwc',
        'USER': 'cwc',
        'PASSWORD': PGPASSWORD,
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Detroit'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FILE_UPLOAD_PERMISSIONS = 0o644

# Project variables

PRODUCTS_PER_PAGE = 15
POSTS_PER_PAGE = 5

ACCESS_TOKEN_FILE = os.path.join(BASE_DIR, 'auth/tokens.txt')
BRAINTREE_ACCESS_TOKEN_SANDBOX = BRAINTREE_ACCESS_TOKEN_PRODUCTION = ''
with open(ACCESS_TOKEN_FILE, 'r', encoding='utf8') as f:
    content = f.readline()
    BRAINTREE_ACCESS_TOKEN_SANDBOX = content[:-1]
    content = f.readline()
    BRAINTREE_ACCESS_TOKEN_PRODUCTION = content[:-1]

MAILGUN_API_KEY_FILE = '%s/auth/mailgun.txt' % BASE_DIR
with open(MAILGUN_API_KEY_FILE, 'r', encoding='utf8') as f:
    content = f.readline()
MAILGUN_API_KEY = content[:-1]

# HTTPS settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True

