# Generated by Django 2.1.4 on 2019-03-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190314_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
