# Generated by Django 2.2.9 on 2020-03-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20190314_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
